import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 'nl' | 'en';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string, fallback?: string) => string;
}

export const translations: Record<Language, Record<string, string>> = {
  nl: {
    // Navigatie
    'Dashboard': 'Dashboard',
    'CRM': 'CRM',
    'Contacts': 'Contacten',
    'Companies': 'Bedrijven',
    'Deals': 'Deals',
    'Activities': 'Activiteiten',
    'Recruitment': 'Werving',
    'Candidates': 'Kandidaten',
    'Jobs': 'Vacatures',
    'Sales': 'Verkoop',
    'Quotes': 'Offertes',
    'Products': 'Producten',
    'Contact Center': 'Klantcontact',
    'Agent Workspace': 'Werkplek Agent',
    'Campaigns': 'Campagnes',
    'Pitch Flows': 'Belscripts',
    '360° View': '360° Overzicht',
    'Gamification': 'Gamificatie',
    'Territories': 'Rayons & Regio\'s',
    'Workflows': 'Werkstromen',
    'Dashboard Builder': 'Dashboard Bouwer',
    'Audit Logs': 'Auditlogboeken',
    'Settings': 'Instellingen',
    'Enhanced': 'Uitgebreid',
    'Admin': 'Beheer',
    'Collapse': 'Inklappen',

    // Header
    'Search contacts, companies, deals...': 'Zoek contacten, bedrijven, deals...',
    'Notifications': 'Meldingen',
    'Mark all read': 'Alles gelezen markeren',
    'Profile': 'Profiel',
    'Log out': 'Uitloggen',
    'Firestore Live': 'Firestore Live',
    'Demo Storage': 'Demo Opslag',
    'Active Call': 'Actief gesprek',
    'No results found': 'Geen resultaten gevonden',

    // Login pagina
    'Welcome to CRMos': 'Welkom bij CRMos',
    'Log in to your account with Google or your credentials': 'Log in op je CRM-account via Google of met je inloggegevens',
    'Sign in with Google': 'Inloggen met Google',
    'Connecting with Google...': 'Verbinden met Google...',
    'Or with email': 'Of met e-mail',
    'Email': 'E-mailadres',
    'Password': 'Wachtwoord',
    'Sign in': 'Inloggen',
    'Signing in...': 'Inloggen...',
    'Demo credentials (any email/password works)': 'Demo-inloggen (elk gewenst e-mail/wachtwoord werkt)',
    'Use Admin Account': 'Admin Demo',
    'Use Agent Account': 'Agent Demo',
    'Tip: Add Firebase credentials in .env': 'Tip: Voeg je Firebase-gegevens toe aan .env om live in te loggen met Google.',

    // Thema & Weergave
    'Theme': 'Thema',
    'Light': 'Licht',
    'Dark': 'Donker',
    'Language': 'Taal',
    'Dutch': 'Nederlands',
    'English': 'Engels',
    'Appearance': 'Weergave',
    'General': 'Algemeen',
    'Primary Color': 'Primaire kleur',
    'Save': 'Opslaan',
    'Saved successfully': 'Succesvol opgeslagen',

    // Knoppen & Acties
    'Add': 'Toevoegen',
    'Edit': 'Bewerken',
    'Delete': 'Verwijderen',
    'Cancel': 'Annuleren',
    'Filter': 'Filteren',
    'Search': 'Zoeken',
    'Export': 'Exporteren',
    'Status': 'Status',
    'Name': 'Naam',
    'Phone': 'Telefoon',
    'Company': 'Bedrijf',
    'Stage': 'Fase',
    'Value': 'Waarde',
    'Due Date': 'Vervaldatum',
    'Priority': 'Prioriteit',

    // Landingspagina & Navigatie
    'Home': 'Home',
    'Features': 'Functionaliteiten',
    'Modules': 'Modules',
    'Pricing': 'Prijzen',
    'FAQ': 'Veelgestelde Vragen',
    'Go to Dashboard': 'Naar Dashboard',
    'Log in': 'Inloggen',
    'Start for Free': 'Start Gratis',
    'Start 14-Day Free Trial': 'Start 14 dagen gratis proefperiode',
    'View Pricing & Plans': 'Bekijk prijzen & pakketten',
    'View Pricing': 'Bekijk prijzen',
    'The Operating System for': 'Het besturingssysteem voor',
    '& Contact Centers': '& Contactcenters',
    'Manage leads, accelerate deals, hire top talent and empower phone agents. An all-in-one platform with realtime pipeline sync, dynamic pitch flows and team gamification.': 'Beheer leads, versnel deals, werf toptalent en geef agents vleugels. Eén geïntegreerd platform met realtime pijplijnsync, dynamische belscripts en teamgamificatie.',
    'No credit card required': 'Geen creditcard vereist',
    'Live within 2 minutes': 'Binnen 2 minuten live',
    'GDPR-proof & Secure': '100% AVG/GDPR-veilig',
    'Average Deal Conversion Rate': 'Hogere dealconversie',
    'Faster Candidate Placements': 'Snellere kandidaatplaatsingen',
    'Realtime Cloud Firestore Sync': 'Realtime Cloud Firestore sync',
    'Lead Response & Follow-up Time': 'Reactietijd per lead',
    'All-in-One Architecture': 'Alles-in-één Architectuur',
    'Everything your team needs under one roof': 'Alles wat je commerciële team nodig heeft onder één dak',
    'No more subscribing to five separate disconnected tools. CRMos provides end-to-end functionality seamlessly connected.': 'Geen vijf losse abonnementen meer. CRMos biedt end-to-end functionaliteit die naadloos op elkaar aansluit.',
    'Smart CRM & Pipelines': 'Slimme CRM & Pijplijnen',
    'Full ATS Recruitment': 'Volledige ATS Recruitment',
    'Gamification & Leaderboard': 'Gamificatie & Leaderboard',
    'Workflows & Automations': 'Werkstromen & Automatisering',
    'Territories & Rayons': 'Rayons & Regio\'s',
    'Sales Pipeline Overview': 'Sales Pijplijn Overzicht',
    'Candidate Tracking & Jobs': 'Kandidaten & Vacatures',
    'Interactive Agent Workspace & Pitch Flow': 'Interactieve Werkplek Agent & Belscripts',
    'Team Leaderboard & Rewards': 'Team Scorebord & Beloningen',
    'Loved by Growth Teams': 'Geliefd bij Groeiteams',
    'What our customers say': 'Wat onze gebruikers zeggen',
    'Frequently Asked Questions': 'Veelgestelde Vragen',
    'Accelerate your sales and recruitment today': 'Versnel je sales en recruitment vandaag nog',
    'Join hundreds of commercial teams that manage deals and candidates seamlessly with CRMos.': 'Sluit je aan bij honderden commerciële teams die deals en kandidaten naadloos beheren met CRMos.',
    'Create Free Account': 'Gratis Account Aanmaken',
    'Realtime Firestore Sync & Google Sign-In': 'Realtime Firestore Sync & Google Inloggen',
    'How quickly can our team get started with CRMos?': 'Hoe snel kan ons team aan de slag met CRMos?',
    'Can I use CRMos with my existing Google / Firebase project?': 'Kan ik CRMos koppelen aan mijn eigen Firebase project?',
    'Is there a free trial period?': 'Is er een gratis proefperiode?',
    'Can we manage multiple departments and roles?': 'Kunnen we meerdere afdelingen en rollen beheren?',

    // Prijzen pagina
    'Transparent Pricing': 'Transparante Tarieven',
    'Simple, transparent pricing for every team': 'Eenvoudige, transparante prijzen voor elk team',
    'Start for free with a 14-day trial. No credit card required. Cancel anytime.': 'Start gratis met een proefperiode van 14 dagen. Geen creditcard nodig. Altijd opzegbaar.',
    'Monthly': 'Maandelijks',
    'Annual': 'Jaarlijks',
    'Save 20%': 'Bespaar 20%',
    'Starter': 'Starter',
    'Professional': 'Professional',
    'Enterprise': 'Enterprise',
    'Most Popular': 'Meest Gekozen',
    'Ultimate Power': 'Ultieme Kracht',
    'For solopreneurs and small sales teams that need clean deal & relationship management.': 'Voor zzp\'ers en kleine salesteams die eenvoudig en krachtig relatiebeheer zoeken.',
    'For ambitious commercial and recruitment teams scaling operations.': 'Voor ambitieuze sales- en recruitmentteams die al hun processen willen stroomlijnen.',
    'For large organizations, call centers and multi-branch agencies needing full control.': 'Voor grote organisaties, contactcenters en scale-ups met maatwerk wensen.',
    'month': 'mnd',
    'What is included:': 'Wat is inbegrepen:',
    'Up to 5 team members': 'Tot 5 teamleden',
    '2,500 Contacts & Companies': 'Tot 2.500 contacten & bedrijven',
    'Visual Sales Kanban Pipeline': 'Visuele saleskanban pijplijn',
    'Activity & Task Tracking': 'Activiteiten- en taakbeheer',
    'Basic Dashboards & Reports': 'Standaard dashboards & rapporten',
    'Email & Communication Log': 'E-mail- & communicatielogboek',
    'Community Support': 'Standaard ondersteuning',
    'Recruitment (ATS) Module': 'Recruitment (ATS) module',
    'Contact Center Workspace & Pitch Flows': 'Contactcenter werkplek & belscripts',
    'Gamification & Commissions': 'Gamificatie & commissies',
    'Territory & Rayon Management': 'Rayon- & regiokaarten',
    'Custom Workflows & Automations': 'Aangepaste workflows & automatiseringen',
    'Up to 15 team members': 'Tot 15 teamleden',
    'Unlimited Contacts, Companies & Deals': 'Onbeperkte contacten, bedrijven & deals',
    'Full ATS Recruitment (Candidates & Jobs)': 'Volledige ATS module (kandidaten & vacatures)',
    'Contact Center Workspace & Campaigns': 'Contactcenter agent werkplek & campagnes',
    'Interactive Pitch Flows (Calling scripts)': 'Interactieve belscripts & beslisbomen',
    'Sales Quotes & Product Catalog': 'Offerte- en productbeheer',
    'No-Code Workflow Automations': 'No-code workflows & triggers',
    'Realtime Cloud Firestore Synchronisation': 'Realtime Cloud Firestore synchronisatie',
    '360° Contact Profile & Scoring': '360° Klantprofiel & engagement scores',
    'Priority Email & Chat Support': 'Prioritaire e-mail & chat ondersteuning',
    'Gamification & Streak System': 'Gamificatie & streaksysteem',
    'Territory & Rayon GeoJSON Maps': 'Rayon GeoJSON postcodetoewijzing',
    'Dedicated Cloud Infrastructure': 'Toegewijde cloudinfrastructuur',
    'Unlimited team members & seats': 'Onbeperkt aantal teamleden & accounts',
    'Everything in Professional included': 'Alles uit Professional inbegrepen',
    'Full Gamification, Badges & Commissions': 'Volledige gamificatie, badges & commissies',
    'Territory Management & Postcode Assignment': 'Rayonbeheer & postcodetoewijzing',
    'Custom Dashboard Builder with KPI widgets': 'Aanpasbare dashboard bouwer met KPI-widgets',
    'Audit Logs & Compliance Tracking': 'Auditlogboeken & AVG-compliance',
    'Custom Webhooks & REST API Access': 'Aangepaste webhooks & REST API-toegang',
    'Dedicated Firestore Cloud Configuration': 'Eigen Firestore cloud projectconfiguratie',
    '99.9% SLA & Dedicated Account Manager': '99,9% SLA & persoonlijke accountmanager',
    'Personal Onboarding & Migration Assistance': 'Persoonlijke onboarding & migratiehulp',
    'Start Enterprise Trial': 'Start Enterprise proefperiode',
    'Detailed Feature Comparison': 'Gedetailleerde Functievergelijking',
    'Compare all capabilities across Starter, Professional and Enterprise.': 'Vergelijk alle mogelijkheden van Starter, Professional en Enterprise.',
    'CRM & Sales Pipeline': 'CRM & Sales Pijplijn',
    'Recruitment & ATS': 'Recruitment & ATS',
    'Contact Center & Telephony': 'Contactcenter & Telefonie',
    'Advanced Operations': 'Geavanceerde Operaties',
    'Unlimited Contacts & Companies': 'Onbeperkte contacten & bedrijven',
    '360° Contact Insights & Score': '360° Klantinzichten & score',
    'Quote Generator & Products': 'Offertegenerator & producten',
    'Candidate Profile Management': 'Kandidaatprofielen & beheer',
    'Job Openings & Pipeline Stages': 'Vacatures & procesfasen',
    'Resume & Skills Matching': 'CV & vaardigheden matching',
    'Agent Call Workspace & Timer': 'Agent belwerkplek & timer',
    'Inbound & Outbound Campaigns': 'Inbound & outbound campagnes',
    'Interactive Pitch Flow Decision Trees': 'Interactieve belscript beslisbomen',
    'No-Code Workflow Triggers': 'No-code workflow triggers',
    'Gamification, Badges & Streaks': 'Gamificatie, badges & streaks',
    'Territory Postcode Polygon Maps': 'Rayon postcode polygonen',
    'Dashboard Widget Builder': 'Dashboard widget bouwer',
    'Audit Logs & Compliance': 'Auditlogboeken & compliance',
    'Frequently Asked Questions About Pricing': 'Veelgestelde Vragen over Prijzen',
    'Can I switch or cancel my plan at any time?': 'Kan ik op elk moment wisselen of opzeggen?',
    'Are there any setup fees or hidden costs?': 'Zijn er opstartkosten of verborgen kosten?',
    'How does the 14-day free trial work?': 'Hoe werkt de 14 dagen gratis proefperiode?',
    'Can I integrate with my existing Firebase project?': 'Kan ik koppelen met mijn eigen Firebase-project?',

    // Registratie & Login
    'Create your CRMos Account': 'Maak je CRMos Account aan',
    'Back to website': 'Terug naar website',
    'Sign up with Google': 'Aanmelden met Google',
    'Full Name': 'Volledige Naam',
    'Company Name': 'Bedrijfsnaam',
    'Business Email': 'Zakelijk E-mailadres',
    'Your Role': 'Jouw Functie / Rol',
    'Sales Director / Managing Director': 'Commercieel Directeur / Algemeen Directeur',
    'Sales / Recruitment Manager': 'Sales- of Recruitmentmanager',
    'Recruiter / ATS Consultant': 'Recruiter / Talent Consultant',
    'Contact Center Agent / Telemarketer': 'Contactcenter Agent / Telemarketeer',
    'Creating account...': 'Account aanmaken...',
    'Already have an account?': 'Heb je al een account?',
    'Log in here': 'Log hier in',
    "Don't have an account yet?": 'Nog geen account?',
    'Ready to accelerate your sales & recruitment?': 'Klaar om je sales & recruitment te versnellen?',
    'Start your 14-day free trial now. No credit card required.': 'Start nu je 14 dagen gratis proefperiode. Geen creditcard vereist.',
    'The complete operational operating system for Sales, Recruitment (ATS) and Contact Centers. Powered by realtime Cloud Firestore and AI-ready automation.': 'Het complete operationele besturingssysteem voor Sales, Recruitment (ATS) en Contactcenters. Aangedreven door realtime Cloud Firestore en AI-automatisering.',
    'GDPR Compliant • Enterprise Grade Security': 'AVG/GDPR-compliant • Enterprise Beveiliging',
    'Product': 'Product',
    'CRM & Pipelines': 'CRM & Pijplijnen',
    'Contact Center Workspace': 'Contactcenter Werkplek',
    'Quotes & Products': 'Offertes & Producten',
    'Gamification & Streaks': 'Gamificatie & Streaks',
    'Territories & Postcodes': 'Rayons & Postcodes',
    'Pricing & Plans': 'Prijzen & Pakketten',
    'Starter Plan (€29)': 'Starter Pakket (€29)',
    'Professional (€79)': 'Professional (€79)',
    'Enterprise (€199)': 'Enterprise (€199)',
    'Feature Comparison': 'Functievergelijking',
    'FAQ & Billing': 'Veelgestelde Vragen & Facturatie',
    'Create Account': 'Account Aanmaken',
    'Help & Support': 'Hulp & Ondersteuning',
    'All rights reserved.': 'Alle rechten voorbehouden.',
    'Privacy Policy': 'Privacybeleid',
    'Terms of Service': 'Algemene Voorwaarden',
    'Security': 'Beveiliging',
  },
  en: {
    // Navigation
    'Dashboard': 'Dashboard',
    'CRM': 'CRM',
    'Contacts': 'Contacts',
    'Companies': 'Companies',
    'Deals': 'Deals',
    'Activities': 'Activities',
    'Recruitment': 'Recruitment',
    'Candidates': 'Candidates',
    'Jobs': 'Jobs',
    'Sales': 'Sales',
    'Quotes': 'Quotes',
    'Products': 'Products',
    'Contact Center': 'Contact Center',
    'Agent Workspace': 'Agent Workspace',
    'Campaigns': 'Campaigns',
    'Pitch Flows': 'Pitch Flows',
    '360° View': '360° View',
    'Gamification': 'Gamification',
    'Territories': 'Territories',
    'Workflows': 'Workflows',
    'Dashboard Builder': 'Dashboard Builder',
    'Audit Logs': 'Audit Logs',
    'Settings': 'Settings',
    'Enhanced': 'Enhanced',
    'Admin': 'Admin',
    'Collapse': 'Collapse',

    // Header
    'Search contacts, companies, deals...': 'Search contacts, companies, deals...',
    'Notifications': 'Notifications',
    'Mark all read': 'Mark all read',
    'Profile': 'Profile',
    'Log out': 'Log out',
    'Firestore Live': 'Firestore Live',
    'Demo Storage': 'Demo Storage',
    'Active Call': 'Active Call',
    'No results found': 'No results found',

    // Login page
    'Welcome to CRMos': 'Welcome to CRMos',
    'Log in to your account with Google or your credentials': 'Log in to your account via Google or credentials',
    'Sign in with Google': 'Sign in with Google',
    'Connecting with Google...': 'Connecting with Google...',
    'Or with email': 'Or with email',
    'Email': 'Email',
    'Password': 'Password',
    'Sign in': 'Sign in',
    'Signing in...': 'Signing in...',
    'Demo credentials (any email/password works)': 'Demo credentials (any email/password works)',
    'Use Admin Account': 'Admin Demo',
    'Use Agent Account': 'Agent Demo',
    'Tip: Add Firebase credentials in .env': 'Tip: Add Firebase credentials in .env to sign in live with Google.',

    // Theme & Appearance
    'Theme': 'Theme',
    'Light': 'Light',
    'Dark': 'Dark',
    'Language': 'Language',
    'Dutch': 'Dutch',
    'English': 'English',
    'Appearance': 'Appearance',
    'General': 'General',
    'Primary Color': 'Primary Color',
    'Save': 'Save',
    'Saved successfully': 'Saved successfully',

    // Buttons & Actions
    'Add': 'Add',
    'Edit': 'Edit',
    'Delete': 'Delete',
    'Cancel': 'Cancel',
    'Filter': 'Filter',
    'Search': 'Search',
    'Export': 'Export',
    'Status': 'Status',
    'Name': 'Name',
    'Phone': 'Phone',
    'Company': 'Company',
    'Stage': 'Stage',
    'Value': 'Value',
    'Due Date': 'Due Date',
    'Priority': 'Priority',

    // Landing Page & Navigation
    'Home': 'Home',
    'Features': 'Features',
    'Modules': 'Modules',
    'Pricing': 'Pricing',
    'FAQ': 'FAQ',
    'Go to Dashboard': 'Go to Dashboard',
    'Log in': 'Log in',
    'Start for Free': 'Start for Free',
    'Start 14-Day Free Trial': 'Start 14-Day Free Trial',
    'View Pricing & Plans': 'View Pricing & Plans',
    'View Pricing': 'View Pricing',
    'The Operating System for': 'The Operating System for',
    '& Contact Centers': '& Contact Centers',
    'Manage leads, accelerate deals, hire top talent and empower phone agents. An all-in-one platform with realtime pipeline sync, dynamic pitch flows and team gamification.': 'Manage leads, accelerate deals, hire top talent and empower phone agents. An all-in-one platform with realtime pipeline sync, dynamic pitch flows and team gamification.',
    'No credit card required': 'No credit card required',
    'Live within 2 minutes': 'Live within 2 minutes',
    'GDPR-proof & Secure': 'GDPR-proof & Secure',
    'Average Deal Conversion Rate': 'Average Deal Conversion Rate',
    'Faster Candidate Placements': 'Faster Candidate Placements',
    'Realtime Cloud Firestore Sync': 'Realtime Cloud Firestore Sync',
    'Lead Response & Follow-up Time': 'Lead Response & Follow-up Time',
    'All-in-One Architecture': 'All-in-One Architecture',
    'Everything your team needs under one roof': 'Everything your team needs under one roof',
    'No more subscribing to five separate disconnected tools. CRMos provides end-to-end functionality seamlessly connected.': 'No more subscribing to five separate disconnected tools. CRMos provides end-to-end functionality seamlessly connected.',
    'Smart CRM & Pipelines': 'Smart CRM & Pipelines',
    'Full ATS Recruitment': 'Full ATS Recruitment',
    'Gamification & Leaderboard': 'Gamification & Leaderboard',
    'Workflows & Automations': 'Workflows & Automations',
    'Territories & Rayons': 'Territories & Rayons',
    'Sales Pipeline Overview': 'Sales Pipeline Overview',
    'Candidate Tracking & Jobs': 'Candidate Tracking & Jobs',
    'Interactive Agent Workspace & Pitch Flow': 'Interactive Agent Workspace & Pitch Flow',
    'Team Leaderboard & Rewards': 'Team Leaderboard & Rewards',
    'Loved by Growth Teams': 'Loved by Growth Teams',
    'What our customers say': 'What our customers say',
    'Frequently Asked Questions': 'Frequently Asked Questions',
    'Accelerate your sales and recruitment today': 'Accelerate your sales and recruitment today',
    'Join hundreds of commercial teams that manage deals and candidates seamlessly with CRMos.': 'Join hundreds of commercial teams that manage deals and candidates seamlessly with CRMos.',
    'Create Free Account': 'Create Free Account',
    'Realtime Firestore Sync & Google Sign-In': 'Realtime Firestore Sync & Google Sign-In',
    'How quickly can our team get started with CRMos?': 'How quickly can our team get started with CRMos?',
    'Can I use CRMos with my existing Google / Firebase project?': 'Can I use CRMos with my existing Google / Firebase project?',
    'Is there a free trial period?': 'Is there a free trial period?',
    'Can we manage multiple departments and roles?': 'Can we manage multiple departments and roles?',

    // Pricing page
    'Transparent Pricing': 'Transparent Pricing',
    'Simple, transparent pricing for every team': 'Simple, transparent pricing for every team',
    'Start for free with a 14-day trial. No credit card required. Cancel anytime.': 'Start for free with a 14-day trial. No credit card required. Cancel anytime.',
    'Monthly': 'Monthly',
    'Annual': 'Annual',
    'Save 20%': 'Save 20%',
    'Starter': 'Starter',
    'Professional': 'Professional',
    'Enterprise': 'Enterprise',
    'Most Popular': 'Most Popular',
    'Ultimate Power': 'Ultimate Power',
    'For solopreneurs and small sales teams that need clean deal & relationship management.': 'For solopreneurs and small sales teams that need clean deal & relationship management.',
    'For ambitious commercial and recruitment teams scaling operations.': 'For ambitious commercial and recruitment teams scaling operations.',
    'For large organizations, call centers and multi-branch agencies needing full control.': 'For large organizations, call centers and multi-branch agencies needing full control.',
    'month': 'month',
    'What is included:': 'What is included:',
    'Up to 5 team members': 'Up to 5 team members',
    '2,500 Contacts & Companies': '2,500 Contacts & Companies',
    'Visual Sales Kanban Pipeline': 'Visual Sales Kanban Pipeline',
    'Activity & Task Tracking': 'Activity & Task Tracking',
    'Basic Dashboards & Reports': 'Basic Dashboards & Reports',
    'Email & Communication Log': 'Email & Communication Log',
    'Community Support': 'Community Support',
    'Recruitment (ATS) Module': 'Recruitment (ATS) Module',
    'Contact Center Workspace & Pitch Flows': 'Contact Center Workspace & Pitch Flows',
    'Gamification & Commissions': 'Gamification & Commissions',
    'Territory & Rayon Management': 'Territory & Rayon Management',
    'Custom Workflows & Automations': 'Custom Workflows & Automations',
    'Up to 15 team members': 'Up to 15 team members',
    'Unlimited Contacts, Companies & Deals': 'Unlimited Contacts, Companies & Deals',
    'Full ATS Recruitment (Candidates & Jobs)': 'Full ATS Recruitment (Candidates & Jobs)',
    'Contact Center Workspace & Campaigns': 'Contact Center Workspace & Campaigns',
    'Interactive Pitch Flows (Calling scripts)': 'Interactive Pitch Flows (Calling scripts)',
    'Sales Quotes & Product Catalog': 'Sales Quotes & Product Catalog',
    'No-Code Workflow Automations': 'No-Code Workflow Automations',
    'Realtime Cloud Firestore Synchronisation': 'Realtime Cloud Firestore Synchronisation',
    '360° Contact Profile & Scoring': '360° Contact Profile & Scoring',
    'Priority Email & Chat Support': 'Priority Email & Chat Support',
    'Gamification & Streak System': 'Gamification & Streak System',
    'Territory & Rayon GeoJSON Maps': 'Territory & Rayon GeoJSON Maps',
    'Dedicated Cloud Infrastructure': 'Dedicated Cloud Infrastructure',
    'Unlimited team members & seats': 'Unlimited team members & seats',
    'Everything in Professional included': 'Everything in Professional included',
    'Full Gamification, Badges & Commissions': 'Full Gamification, Badges & Commissions',
    'Territory Management & Postcode Assignment': 'Territory Management & Postcode Assignment',
    'Custom Dashboard Builder with KPI widgets': 'Custom Dashboard Builder with KPI widgets',
    'Audit Logs & Compliance Tracking': 'Audit Logs & Compliance Tracking',
    'Custom Webhooks & REST API Access': 'Custom Webhooks & REST API Access',
    'Dedicated Firestore Cloud Configuration': 'Dedicated Firestore Cloud Configuration',
    '99.9% SLA & Dedicated Account Manager': '99.9% SLA & Dedicated Account Manager',
    'Personal Onboarding & Migration Assistance': 'Personal Onboarding & Migration Assistance',
    'Start Enterprise Trial': 'Start Enterprise Trial',
    'Detailed Feature Comparison': 'Detailed Feature Comparison',
    'Compare all capabilities across Starter, Professional and Enterprise.': 'Compare all capabilities across Starter, Professional and Enterprise.',
    'CRM & Sales Pipeline': 'CRM & Sales Pipeline',
    'Recruitment & ATS': 'Recruitment & ATS',
    'Contact Center & Telephony': 'Contact Center & Telephony',
    'Advanced Operations': 'Advanced Operations',
    'Unlimited Contacts & Companies': 'Unlimited Contacts & Companies',
    '360° Contact Insights & Score': '360° Contact Insights & Score',
    'Quote Generator & Products': 'Quote Generator & Products',
    'Candidate Profile Management': 'Candidate Profile Management',
    'Job Openings & Pipeline Stages': 'Job Openings & Pipeline Stages',
    'Resume & Skills Matching': 'Resume & Skills Matching',
    'Agent Call Workspace & Timer': 'Agent Call Workspace & Timer',
    'Inbound & Outbound Campaigns': 'Inbound & Outbound Campaigns',
    'Interactive Pitch Flow Decision Trees': 'Interactive Pitch Flow Decision Trees',
    'No-Code Workflow Triggers': 'No-Code Workflow Triggers',
    'Gamification, Badges & Streaks': 'Gamification, Badges & Streaks',
    'Territory Postcode Polygon Maps': 'Territory Postcode Polygon Maps',
    'Dashboard Widget Builder': 'Dashboard Widget Builder',
    'Audit Logs & Compliance': 'Audit Logs & Compliance',
    'Frequently Asked Questions About Pricing': 'Frequently Asked Questions About Pricing',
    'Can I switch or cancel my plan at any time?': 'Can I switch or cancel my plan at any time?',
    'Are there any setup fees or hidden costs?': 'Are there any setup fees or hidden costs?',
    'How does the 14-day free trial work?': 'How does the 14-day free trial work?',
    'Can I integrate with my existing Firebase project?': 'Can I integrate with my existing Firebase project?',

    // Registration & Login
    'Create your CRMos Account': 'Create your CRMos Account',
    'Back to website': 'Back to website',
    'Sign up with Google': 'Sign up with Google',
    'Full Name': 'Full Name',
    'Company Name': 'Company Name',
    'Business Email': 'Business Email',
    'Your Role': 'Your Role',
    'Sales Director / Managing Director': 'Sales Director / Managing Director',
    'Sales / Recruitment Manager': 'Sales / Recruitment Manager',
    'Recruiter / ATS Consultant': 'Recruiter / ATS Consultant',
    'Contact Center Agent / Telemarketer': 'Contact Center Agent / Telemarketer',
    'Creating account...': 'Creating account...',
    'Already have an account?': 'Already have an account?',
    'Log in here': 'Log in here',
    "Don't have an account yet?": "Don't have an account yet?",
    'Ready to accelerate your sales & recruitment?': 'Ready to accelerate your sales & recruitment?',
    'Start your 14-day free trial now. No credit card required.': 'Start your 14-day free trial now. No credit card required.',
    'The complete operational operating system for Sales, Recruitment (ATS) and Contact Centers. Powered by realtime Cloud Firestore and AI-ready automation.': 'The complete operational operating system for Sales, Recruitment (ATS) and Contact Centers. Powered by realtime Cloud Firestore and AI-ready automation.',
    'GDPR Compliant • Enterprise Grade Security': 'GDPR Compliant • Enterprise Grade Security',
    'Product': 'Product',
    'CRM & Pipelines': 'CRM & Pipelines',
    'Contact Center Workspace': 'Contact Center Workspace',
    'Quotes & Products': 'Quotes & Products',
    'Gamification & Streaks': 'Gamification & Streaks',
    'Territories & Postcodes': 'Territories & Postcodes',
    'Pricing & Plans': 'Pricing & Plans',
    'Starter Plan (€29)': 'Starter Plan (€29)',
    'Professional (€79)': 'Professional (€79)',
    'Enterprise (€199)': 'Enterprise (€199)',
    'Feature Comparison': 'Feature Comparison',
    'FAQ & Billing': 'FAQ & Billing',
    'Create Account': 'Create Account',
    'Help & Support': 'Help & Support',
    'All rights reserved.': 'All rights reserved.',
    'Privacy Policy': 'Privacy Policy',
    'Terms of Service': 'Terms of Service',
    'Security': 'Security',
  },
};

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'nl',

      setLanguage: (language) => set({ language }),

      toggleLanguage: () => {
        const nextLang: Language = get().language === 'nl' ? 'en' : 'nl';
        set({ language: nextLang });
      },

      t: (key: string, fallback?: string): string => {
        const currentLang = get().language;
        return translations[currentLang]?.[key] || fallback || key;
      },
    }),
    {
      name: 'crmos-language-storage',
    }
  )
);

/**
 * React hook for quick translation in functional components
 */
export function useTranslation() {
  const { language, setLanguage, toggleLanguage, t } = useLanguageStore();
  return { language, setLanguage, toggleLanguage, t };
}
